# Your Website Title
title: Ke Li

# Your Website URL
url: 'https://likemelike.github.io/'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Ke Li
tagline: Route Planning, Spatio-temporal Data Mining, High-dimensional Index
pic: profile.jpg # profile.png can be found at /assets/images/profile.png
description: Ph.D. candidate at UESTC
description_tiny: ''
email: like_like@std.uestc.edu.cn
website: likemelike.github.io # do not add http://
linkedin: realmelvinchng
github: https://github.com/likemelike
twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
